### ISSUE TITLE
Log instead of print

### ISSUE THREAD

**Issue by pysailor** [collective/Products.PrintingMailHost#1]
Hi @mauritsvanrees or @claytron ,

I know it would have been more proper to open a ticket _first_  and work in a branch...
Anyway last year I committed a change so that e-mails get written to the log instead of printed to stdout (f1991ac45160f9ef85589ffdf4dc385567522d7b), so that PMH is more useful in testing environments that don't run in foreground. Plus I made some structural changes like renaming .txt files to .rst.

Could you please review these changes and if you're OK cut a new release? I'd also be happy to make a release myself. My pypi username is "thomasw".

thanks,
Wolfgang

**Comment by mauritsvanrees** [comment]
I have released 0.8.
