### ISSUE TITLE
Send to fixed mailaddress

### ISSUE THREAD

**Issue by maartenkling** [collective/Products.PrintingMailHost#2]
As i love this product in development, i sometimes need the real email to send it to the customer to show how it will look like, i order to do this i need to configure everything so the mail is send to a address i personally own.

The coolest feature would be you could configure a fixed mail-address in buildout.cfg and a flag for printingmailhost that all mails are send to that address only, or printend like it does now, even if the site is sending it somewhere else.

**Comment by mauritsvanrees** [comment]
This was merged.
